### ISSUE TITLE
Make sure jQuery is enqueued.

### ISSUE THREAD

**Issue by vitaligent** [VR51/FlowType-WP#1]
This plugin doesn't enqueue jQuery. This can be seen if you use the underscores theme while logged out of the site.

Thanks for writing this plugin. I think FlowType is great.

**Comment by VR51** [comment]
Thanks for spotting this oversight. Was relying on jQuery being enqueued by themes. Will upload a new version of the plugin in the next few days. The only change will be the enqueue of jQuery.

Be careful if you upgrade because any customizations to the plugin's index.php file will be overwritten (you'll need to copy them back in).

**Comment by VR51** [comment]
Plugin updated to add jQuery enqueuing.
